/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LocalAgentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");
var CHAT_PATHS = {
  /** OpenAI-compatible endpoint (works with LM Studio, vLLM, Ollama v0.1.24+). */
  openai: "/v1/chat/completions",
  /** Ollama-native chat endpoint. */
  ollama: "/api/chat"
};
function normaliseEndpoint(url) {
  return url.replace(/\/+$/, "");
}
function buildRequest(url, body) {
  return {
    url,
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body),
    throw: false
    // we handle HTTP errors ourselves
  };
}
function parseJsonFromLLM(raw) {
  const fenceRegex = /```(?:json)?\s*\n?([\s\S]*?)```/;
  const fenceMatch = raw.match(fenceRegex);
  const candidate = fenceMatch ? fenceMatch[1].trim() : raw.trim();
  try {
    return JSON.parse(candidate);
  } catch (e) {
    const start = candidate.indexOf("{");
    const end = candidate.lastIndexOf("}");
    if (start !== -1 && end !== -1 && end > start) {
      try {
        return JSON.parse(candidate.substring(start, end + 1));
      } catch (e2) {
        return null;
      }
    }
    return null;
  }
}
var LocalLLMClient = class {
  constructor(config) {
    this.endpoint = normaliseEndpoint(config.endpoint);
    this.model = config.model;
  }
  // ---- Configuration mutations --------------------------------------------
  /** Update the endpoint at runtime (e.g. when settings change). */
  setEndpoint(endpoint) {
    this.endpoint = normaliseEndpoint(endpoint);
  }
  /** Update the model at runtime. */
  setModel(model) {
    this.model = model;
  }
  // ---- Core API -----------------------------------------------------------
  /**
   * Send a chat completion request to the local LLM.
   *
   * The client first attempts the OpenAI-compatible `/v1/chat/completions`
   * endpoint. If that returns a 404, it falls back to Ollama's native
   * `/api/chat` endpoint, adapting the request/response format accordingly.
   *
   * @param messages  The conversation history to send.
   * @param temperature  Sampling temperature (0-2). Defaults to 0.3 for
   *                     deterministic classification tasks.
   * @returns A normalised `ChatCompletionResponse`.
   * @throws If both endpoints fail or the server is unreachable.
   */
  async chat(messages, temperature = 0.3) {
    try {
      const result = await this.chatOpenAI(messages, temperature);
      return result;
    } catch (err) {
      const is404 = err instanceof Error && err.message.includes("404");
      if (!is404) {
        throw err;
      }
    }
    return this.chatOllama(messages, temperature);
  }
  /**
   * Convenience wrapper: single-turn prompt with a system message.
   */
  async prompt(systemPrompt, userPrompt, temperature = 0.3) {
    const messages = [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ];
    const response = await this.chat(messages, temperature);
    return response.content;
  }
  // ---- Connectivity check -------------------------------------------------
  /**
   * Verify that the configured endpoint is reachable.
   *
   * @returns `true` if the server responds, `false` otherwise.
   */
  async ping() {
    try {
      const urls = [
        `${this.endpoint}/api/tags`,
        `${this.endpoint}/v1/models`
      ];
      for (const url of urls) {
        try {
          const res = await (0, import_obsidian.requestUrl)({
            url,
            method: "GET",
            throw: false
          });
          if (res.status >= 200 && res.status < 300) {
            return true;
          }
        } catch (e) {
        }
      }
      return false;
    } catch (e) {
      return false;
    }
  }
  // ---- Private helpers ----------------------------------------------------
  /**
   * Send a request to the OpenAI-compatible chat endpoint.
   */
  async chatOpenAI(messages, temperature) {
    var _a, _b, _c, _d;
    const url = `${this.endpoint}${CHAT_PATHS.openai}`;
    const body = {
      model: this.model,
      messages,
      temperature,
      stream: false
    };
    const res = await (0, import_obsidian.requestUrl)(buildRequest(url, body));
    if (res.status === 404) {
      throw new Error(`404: OpenAI-compatible endpoint not found at ${url}`);
    }
    if (res.status < 200 || res.status >= 300) {
      throw new Error(
        `LLM API error (${res.status}): ${(_a = res.text) == null ? void 0 : _a.substring(0, 300)}`
      );
    }
    const data = res.json;
    const choice = (_b = data == null ? void 0 : data.choices) == null ? void 0 : _b[0];
    return {
      content: (_d = (_c = choice == null ? void 0 : choice.message) == null ? void 0 : _c.content) != null ? _d : "",
      model: data == null ? void 0 : data.model,
      usage: data == null ? void 0 : data.usage
    };
  }
  /**
   * Send a request to the Ollama-native chat endpoint.
   */
  async chatOllama(messages, temperature) {
    var _a, _b, _c;
    const url = `${this.endpoint}${CHAT_PATHS.ollama}`;
    const body = {
      model: this.model,
      messages,
      stream: false,
      options: {
        temperature
      }
    };
    const res = await (0, import_obsidian.requestUrl)(buildRequest(url, body));
    if (res.status < 200 || res.status >= 300) {
      throw new Error(
        `LLM API error (${res.status}): ${(_a = res.text) == null ? void 0 : _a.substring(0, 300)}`
      );
    }
    const data = res.json;
    return {
      content: (_c = (_b = data == null ? void 0 : data.message) == null ? void 0 : _b.content) != null ? _c : "",
      model: data == null ? void 0 : data.model,
      usage: (data == null ? void 0 : data.prompt_eval_count) ? {
        prompt_tokens: data.prompt_eval_count,
        completion_tokens: data.eval_count
      } : void 0
    };
  }
};

// src/classifier.ts
var import_obsidian2 = require("obsidian");
var PILLARS = [
  "10_Work_&_Management",
  "20_Academic_CS",
  "30_Life_&_Creations",
  "40_Self_Hosted_Lab",
  "00_Inbox"
];
var CLASSIFICATION_SYSTEM_PROMPT = `You are a highly precise classification engine. Organize knowledge into ONE of the following Five Pillars exact names:
- 10_Work_&_Management: Content related to team leading, meetings, project management, and professional networking.
- 20_Academic_CS: Content related to Computer Science degree studies, UoPeople assignments, and technical learning.
- 30_Life_&_Creations: Content related to food blogging (local delicacies in central Taiwan/Japan), travel plans, and personal hobbies.
- 40_Self_Hosted_Lab: Content related to home server setup (Mac Mini 2011), Docker, self-hosted services, and AI tool testing.
- 00_Inbox: The default fallback if no strong match is found.

You MUST respond with valid JSON only. Keep the response exactly in this schema:
{
  "category": "<one of the five exact folder names above>",
  "tags": ["<tag1>", "<tag2>", "<tag3>"],
  "confidence": <float between 0.0 and 1.0>
}

Rules:
1. "category" MUST exactly match one of the Five Pillars.
2. "tags" must contain 3-5 specific sub-topics (e.g., "#Docker", "#NantouFood").
3. "confidence" must reflect your certainty.
4. Do NOT include markdown fences, code blocks, or text outside the JSON object.`;
var ClassificationEngine = class {
  constructor(app, apiClient, classificationTemperature) {
    this.app = app;
    this.apiClient = apiClient;
    this.classificationTemperature = classificationTemperature;
  }
  async classifyFile(file) {
    var _a;
    try {
      const content = await this.app.vault.read(file);
      const bodyContent = this.stripFrontmatter(content);
      if (bodyContent.includes("%% AI_Classified_at:")) {
        new import_obsidian2.Notice(`File "${file.basename}" is already classified.`);
        return;
      }
      new import_obsidian2.Notice(`Classifying "${file.basename}"...`);
      const rawResponse = await this.apiClient.prompt(
        CLASSIFICATION_SYSTEM_PROMPT,
        bodyContent,
        this.classificationTemperature
      );
      const parsed = parseJsonFromLLM(rawResponse);
      if (!parsed || typeof parsed.category !== "string" || !Array.isArray(parsed.tags) || typeof parsed.confidence !== "number") {
        new import_obsidian2.Notice("LLM returned unexpected JSON structure. Check console.");
        console.error("[ClassificationEngine] Invalid response:", rawResponse);
        return;
      }
      const { category, tags, confidence } = parsed;
      let finalCategory = category;
      if (!PILLARS.includes(finalCategory)) {
        finalCategory = "00_Inbox";
      }
      const tagsToAdd = [...tags];
      let shouldMove = false;
      if (confidence < 0.7) {
        tagsToAdd.push("#AI-Uncertain");
      } else {
        const parentPath = ((_a = file.parent) == null ? void 0 : _a.path) || "";
        if (parentPath === "00_Inbox" && finalCategory !== "00_Inbox") {
          shouldMove = true;
        }
      }
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        frontmatter["category"] = finalCategory;
        const existingTags = Array.isArray(frontmatter["tags"]) ? frontmatter["tags"] : [];
        frontmatter["tags"] = Array.from(/* @__PURE__ */ new Set([...existingTags, ...tagsToAdd]));
        delete frontmatter["last_classified"];
      });
      const timestamp = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
      const comment = `

%% AI_Classified_at: ${timestamp} %%`;
      await this.app.vault.append(file, comment);
      if (shouldMove) {
        await this.moveFileToCategory(file, finalCategory);
        new import_obsidian2.Notice(`Note moved to ${finalCategory}`);
      } else {
        if (confidence < 0.7) {
          new import_obsidian2.Notice(`Classification complete (low confidence). Kept as Inbox/Uncertain.`);
        } else {
          new import_obsidian2.Notice(`Classification complete.`);
        }
      }
    } catch (err) {
      console.error("[ClassificationEngine] Error processing file:", err);
      new import_obsidian2.Notice(`Classification failed: ${err.message}`);
    }
  }
  async moveFileToCategory(file, category) {
    const destFolder = (0, import_obsidian2.normalizePath)(category);
    const abstractFolder = this.app.vault.getAbstractFileByPath(destFolder);
    if (!abstractFolder) {
      await this.app.vault.createFolder(destFolder);
    }
    const newPath = (0, import_obsidian2.normalizePath)(`${category}/${file.name}`);
    await this.app.vault.rename(file, newPath);
  }
  stripFrontmatter(content) {
    const fmRegex = /^---\s*\n[\s\S]*?\n---\s*\n?/;
    return content.replace(fmRegex, "").trim();
  }
};

// src/refiner.ts
var import_obsidian3 = require("obsidian");
var PILLARS2 = [
  "10_Work_&_Management",
  "20_Academic_CS",
  "30_Life_&_Creations",
  "40_Self_Hosted_Lab",
  "00_Inbox"
];
var REFINER_SYSTEM_PROMPT = `You are an expert knowledge refiner and summarisation engine. Your job is to process raw notes and articles, and extract the highest quality signal from the noise.

You will output exactly ONE structured JSON object. Read the input note carefully and perform these four operations:

1. SUMMARY: Provide a concise summary of the core idea.
2. KEYWORDS: Extract key technical terms and provide an English-to-Traditional Chinese glossary. If the original text is already in Chinese, you can ignore this or provide English terms for Chinese concepts.
3. HIGHLIGHTS: Extract ONLY the highly valuable, useful paragraphs or sentences. Rewrite them clearly. Remove all boilerplate, fluff, and unnecessary context.
4. ATOMIZATION: If there are distinct, highly valuable techniques, concepts, or mental models (e.g. a specific "Thread Management" trick), extract them into separate atomic notes.
5. CLASSIFICATION: Classify the content into exactly ONE of the Five Pillars.

Five Pillars:
- 10_Work_&_Management
- 20_Academic_CS
- 30_Life_&_Creations
- 40_Self_Hosted_Lab
- 00_Inbox

Expected JSON structure:
{
  "summary": "Concise summary...",
  "keywords": [
    { "en": "English Term", "zh": "Traditional Chinese Translation" }
  ],
  "highlights": [
    "Useful paragraph 1...",
    "Useful paragraph 2..."
  ],
  "atomicNotes": [
    {
      "title": "Specific Concept Name",
      "content": "Detailed explanation of the concept...",
      "tags": ["#tag1", "#tag2"]
    }
  ],
  "category": "20_Academic_CS",
  "tags": ["#tag1", "#tag2", "#tag3"],
  "confidence": 0.95
}

Rules:
1. "category" MUST exactly match one of the Five Pillars.
2. "tags" should contain 3-5 sub-topics.
3. Be highly selective with highlights. If the whole text is garbage, "highlights" can be empty.
4. "atomicNotes" should only contain highly specific, reusable insights. Do not force it if there are no distinct concepts.
5. All text in "summary", "keywords" (zh), "highlights", and "atomicNotes.content" should be in Traditional Chinese (zh-TW).
6. Do NOT include markdown fences, code blocks, or text outside the JSON object. Just valid JSON.`;
var NoteRefinerEngine = class {
  constructor(app, apiClient, temperature) {
    this.app = app;
    this.apiClient = apiClient;
    this.temperature = temperature;
  }
  async refineFile(file) {
    var _a;
    try {
      const originalContent = await this.app.vault.read(file);
      const bodyContent = this.stripFrontmatter(originalContent);
      if (bodyContent.trim().length === 0) {
        new import_obsidian3.Notice("Note is empty. Nothing to refine.");
        return;
      }
      new import_obsidian3.Notice(`Refining "${file.basename}"... This might take a while.`);
      const rawResponse = await this.apiClient.prompt(
        REFINER_SYSTEM_PROMPT,
        bodyContent,
        this.temperature
      );
      const parsed = parseJsonFromLLM(rawResponse);
      if (!parsed || !parsed.summary || !Array.isArray(parsed.highlights)) {
        new import_obsidian3.Notice("LLM returned unexpected JSON structure. Check console.");
        console.error("[NoteRefinerEngine] Invalid response:", rawResponse);
        return;
      }
      const atomicLinks = [];
      if (parsed.atomicNotes && Array.isArray(parsed.atomicNotes)) {
        for (const atomic of parsed.atomicNotes) {
          const fileName = this.sanitizeFileName(atomic.title);
          const link = await this.createAtomicNote(fileName, atomic, parsed.category);
          if (link) {
            atomicLinks.push(link);
          }
        }
      }
      const refinedBody = this.buildRefinedContent(parsed, atomicLinks);
      let finalCategory = parsed.category;
      if (!PILLARS2.includes(finalCategory)) {
        finalCategory = "00_Inbox";
      }
      const tagsToAdd = [...parsed.tags || []];
      let shouldMove = false;
      if (parsed.confidence < 0.7) {
        tagsToAdd.push("#AI-Uncertain");
      } else {
        const parentPath = ((_a = file.parent) == null ? void 0 : _a.path) || "";
        if (parentPath === "00_Inbox" && finalCategory !== "00_Inbox") {
          shouldMove = true;
        }
      }
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        frontmatter["category"] = finalCategory;
        const existingTags = Array.isArray(frontmatter["tags"]) ? frontmatter["tags"] : [];
        frontmatter["tags"] = Array.from(/* @__PURE__ */ new Set([...existingTags, ...tagsToAdd]));
        frontmatter["refined"] = true;
      });
      const contentWithNewFrontmatter = await this.app.vault.read(file);
      const frontmatterMatch = contentWithNewFrontmatter.match(/^---\s*\n[\s\S]*?\n---\s*\n?/);
      const frontmatterStr = frontmatterMatch ? frontmatterMatch[0] : "";
      const newFullContent = frontmatterStr + refinedBody;
      await this.app.vault.modify(file, newFullContent);
      if (shouldMove) {
        await this.moveFileToCategory(file, finalCategory);
        new import_obsidian3.Notice(`Refined & moved to ${finalCategory}`);
      } else {
        new import_obsidian3.Notice(`Refinement complete.`);
      }
    } catch (err) {
      console.error("[NoteRefinerEngine] Error processing file:", err);
      new import_obsidian3.Notice(`Refinement failed: ${err.message}`);
    }
  }
  buildRefinedContent(parsed, atomicLinks) {
    const parts = [];
    parts.push(`> [!summary] Summary`);
    parts.push(`> ${parsed.summary.replace(/\\n/g, "\\n> ")}`);
    parts.push(``);
    if (parsed.keywords && Array.isArray(parsed.keywords) && parsed.keywords.length > 0) {
      parts.push(`> [!info] \u95DC\u9375\u5B57\u5C0D\u7167\u8868 (Keywords)`);
      for (const kw of parsed.keywords) {
        parts.push(`> - **${kw.en}**: ${kw.zh}`);
      }
      parts.push(``);
    }
    parts.push(`## Highlights (\u9AD8\u4EAE)`);
    if (parsed.highlights.length > 0) {
      for (const hl of parsed.highlights) {
        parts.push(`${hl}`);
        parts.push(``);
      }
    } else {
      parts.push(`*(No specific useful paragraphs extracted)*`);
      parts.push(``);
    }
    if (atomicLinks.length > 0) {
      parts.push(`## \u539F\u5B50\u5316\u7B46\u8A18 (Atomic Concepts)`);
      for (const link of atomicLinks) {
        parts.push(`- ${link}`);
      }
      parts.push(``);
    }
    const timestamp = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    parts.push(`%% AI_Refined_at: ${timestamp} %%`);
    return parts.join("\n");
  }
  async createAtomicNote(fileName, data, category) {
    try {
      let finalCategory = category;
      if (!PILLARS2.includes(finalCategory)) {
        finalCategory = "00_Inbox";
      }
      const destFolder = (0, import_obsidian3.normalizePath)(finalCategory);
      const abstractFolder = this.app.vault.getAbstractFileByPath(destFolder);
      if (!abstractFolder) {
        await this.app.vault.createFolder(destFolder);
      }
      let attempt = 0;
      let finalPath = (0, import_obsidian3.normalizePath)(`${finalCategory}/${fileName}.md`);
      while (this.app.vault.getAbstractFileByPath(finalPath)) {
        attempt++;
        finalPath = (0, import_obsidian3.normalizePath)(`${finalCategory}/${fileName} ${attempt}.md`);
      }
      const timestamp = (/* @__PURE__ */ new Date()).toISOString();
      const tagsStr = data.tags && data.tags.length > 0 ? `tags:
  - ${data.tags.map((t) => t.replace(/^#/, "")).join("\\n  - ")}` : "tags: []";
      const fullContent = `---
type: atomic-note
category: ${finalCategory}
${tagsStr}
created: ${timestamp}
---

# ${fileName}

${data.content}
`;
      await this.app.vault.create(finalPath, fullContent);
      return `[[${finalPath.replace(".md", "")}|${fileName}]]`;
    } catch (err) {
      console.error("[NoteRefinerEngine] Failed to create atomic note:", err);
      return null;
    }
  }
  sanitizeFileName(name) {
    return name.replace(/[\\/:"*?<>|#^\[\]]/g, "").trim() || "Atomic Note";
  }
  async moveFileToCategory(file, category) {
    const destFolder = (0, import_obsidian3.normalizePath)(category);
    const abstractFolder = this.app.vault.getAbstractFileByPath(destFolder);
    if (!abstractFolder) {
      await this.app.vault.createFolder(destFolder);
    }
    const newPath = (0, import_obsidian3.normalizePath)(`${category}/${file.name}`);
    await this.app.vault.rename(file, newPath);
  }
  stripFrontmatter(content) {
    const fmRegex = /^---\s*\n[\s\S]*?\n---\s*\n?/;
    return content.replace(fmRegex, "").trim();
  }
};

// src/articleProcessor.ts
var import_obsidian4 = require("obsidian");
var PILLARS3 = [
  "10_Work_&_Management",
  "20_Academic_CS",
  "30_Life_&_Creations",
  "40_Self_Hosted_Lab",
  "99_Uncategorized"
];
var ARTICLE_PROCESSOR_PROMPT = `\u95B1\u8B80\u4F7F\u7528\u8005\u63D0\u4F9B\u7684\u6587\u7AE0\u5167\u5BB9\uFF0C\u4E26\u56B4\u683C\u6309\u7167\u4EE5\u4E0B\u56DB\u500B\u6B65\u9A5F\u8655\u7406\uFF0C\u6700\u7D42\u6539\u5BEB\u70BA\u4E00\u500B\u5B8C\u6574\u7684 Markdown \u683C\u5F0F\u7B46\u8A18\u3002

## Step 1: \u5EFA\u7ACB\u6A19\u6E96\u5316 YAML Frontmatter
\u8ACB\u6839\u64DA\u6587\u7AE0\u5167\u5BB9\uFF0C\u63D0\u53D6\u4E2D\u7E7C\u8CC7\u6599\u4E26\u751F\u6210 YAML \u5340\u584A\u3002
- type: reference
- source: {SOURCE_URL}
- captured: {CAPTURED_DATE}
- category: \u5FC5\u9808\u662F\u4EE5\u4E0B\u4E94\u5927\u5206\u985E\uFF08Five Pillars\uFF09\u7684\u5176\u4E2D\u4E00\u500B\u7CBE\u78BA\u540D\u7A31\uFF1A
  - 10_Work_&_Management (\u5718\u968A\u5E36\u9818\u3001\u5C08\u6848\u7BA1\u7406\u3001\u4EBA\u969B\u3001\u8077\u5834)
  - 20_Academic_CS (\u8A08\u7B97\u6A5F\u79D1\u5B78\u3001\u5B78\u4F4D\u3001\u7A0B\u5F0F\u958B\u767C\u3001\u6280\u8853)
  - 30_Life_&_Creations (\u751F\u6D3B\u98F2\u98DF\u3001\u65C5\u904A\u3001\u500B\u4EBA\u8208\u8DA3)
  - 40_Self_Hosted_Lab (\u4F3A\u670D\u5668\u3001Docker\u3001\u81EA\u8A17\u7BA1\u3001AI\u5DE5\u5177)
  - 99_Uncategorized (\u7121\u6CD5\u6B78\u985E\u5230\u4EE5\u4E0A\u56DB\u5927\u985E\u5225\u6642\u653E\u9019\u88E1)
- tags: [\u63D0\u53D6 2-3 \u500B\u8207\u4E3B\u984C\u76F8\u95DC\u7684\u6A19\u7C64\uFF0C\u5FC5\u9808\u5305\u542B #web-clippings\uFF0C\u4E26\u8996\u60C5\u6CC1\u52A0\u4E0A #status/to-process \u6216 #status/evergreen]

## Step 2: \u64B0\u5BEB\u300C\u4E00\u53E5\u8A71\u7E3D\u7D50 (One-Sentence Summary)\u300D
\u5728 YAML \u5340\u584A\u4E0B\u65B9\uFF0C\u8ACB\u7528\u4E00\u53E5\u7CBE\u7149\u7684\u8A71\uFF08\u4E0D\u8D85\u904E 50 \u5B57\uFF09\u7E3D\u7D50\u9019\u7BC7\u6587\u7AE0\u7684\u6838\u5FC3\u50F9\u503C\u6216\u89E3\u6C7A\u7684\u554F\u984C\uFF0C\u8B93\u672A\u4F86\u7684\u8B80\u8005\uFF08\u4F7F\u7528\u8005\u672C\u4EBA\uFF09\u80FD\u5728\u4E00\u79D2\u5167\u6C7A\u5B9A\u662F\u5426\u9700\u8981\u7E7C\u7E8C\u95B1\u8B80\u3002

## Step 3: \u77E5\u8B58\u84B8\u993E\u8207\u91CD\u9EDE\u63D0\u53D6 (Distillation)
\u4E0D\u8981\u539F\u6587\u7167\u6284\u3002\u8ACB\u904E\u6FFE\u6389\u5EE2\u8A71\u8207\u5197\u9577\u7684\u92EA\u9673\uFF0C\u63D0\u53D6\u6587\u7AE0\u4E2D\u6700\u5177\u50F9\u503C\u7684 3 \u5230 5 \u500B\u6838\u5FC3\u89C0\u9EDE\u6216\u5BE6\u7528\u6280\u5DE7\uFF0C\u4E26\u4F7F\u7528 Markdown \u7684\u689D\u5217\u5F0F\uFF08Bullet points\uFF09\u6216\u5F15\u7528\u5340\u584A\uFF08>\uFF09\u5448\u73FE\u3002

## Step 4: \u539F\u5B50\u5316\u6982\u5FF5\u6A19\u8A18\u8207\u7368\u7ACB\u8403\u53D6 (Atomization & Extraction)
\u9019\u662F\u6700\u91CD\u8981\u7684\u4E00\u6B65\u3002\u8ACB\u4E3B\u52D5\u8FA8\u8B58\u6587\u7AE0\u4E2D\u51FA\u73FE\u7684\u300C\u7368\u7ACB\u91CD\u8981\u6982\u5FF5\u300D\u3001\u300C\u5C08\u6709\u540D\u8A5E\u300D\u3001\u300C\u6846\u67B6\u300D\u6216\u300C\u6F14\u7B97\u6CD5\u300D\uFF08\u4F8B\u5982\uFF1A\u7279\u5B9A\u7684\u7BA1\u7406\u5DE5\u5177\u3001\u7CFB\u7D71\u67B6\u69CB\u540D\u7A31\u7B49\uFF09\u3002
1. \u5728\u91CD\u9EDE\u63D0\u53D6\u7684\u6B63\u6587\u4E2D\uFF0C\u5C07\u9019\u4E9B\u8A5E\u5F59\u4F7F\u7528\u96D9\u5C64\u4E2D\u62EC\u865F \`[[ ]]\` \u5305\u8986\u8D77\u4F86\u3002
2. \u5728\u6574\u4EFD\u7B46\u8A18\u7684\u6700\u672B\u7AEF\uFF0C\u8ACB **\u52D9\u5FC5** \u4F7F\u7528\u4EE5\u4E0B \`<atomic-notes>\` \u7684 XML \u7D50\u69CB\uFF0C\u70BA\u6BCF\u4E00\u500B\u6A19\u8A18 \`[[ ]]\` \u7684\u5C08\u6709\u540D\u8A5E\u7522\u751F\u7368\u7ACB\u7B46\u8A18\u5167\u5BB9\uFF08\u5305\u542B\u5B9A\u7FA9\u3001\u7528\u9014\u53CA\u95DC\u806F\u6A19\u7C64\uFF09\u3002

---
# Output Template (\u56B4\u683C\u9075\u5FAA\u6B64\u683C\u5F0F\u8F38\u51FA\uFF0C\u4E0D\u8981\u8F38\u51FA\u4EFB\u4F55\u5176\u4ED6\u591A\u9918\u7684\u5C0D\u8A71\u6587\u5B57)

---
type: reference
source: {SOURCE_URL}
captured: {CAPTURED_DATE}
category: {Category}
tags: #web-clippings #{Tag1} #{Tag2} #status/to-process
---
[\u4E00\u53E5\u8A71\u7E3D\u7D50\u653E\u5728\u9019\u88E1]

## \u91CD\u9EDE\u63D0\u53D6
- [[\u5C08\u6709\u540D\u8A5E]] \u89C0\u9EDE\u4E00...
- \u89C0\u9EDE\u4E8C...
> \u5F15\u7528\u91CD\u8981\u6280\u5DE7...

<atomic-notes>
<note title="\u5C08\u6709\u540D\u8A5E" tags="#tag1 #tag2" category="20_Academic_CS">
\u9019\u88E1\u586B\u5BEB\u5C0D\u8A72\u5C08\u6709\u540D\u8A5E\u7684\u8A73\u7D30\u89E3\u91CB\u3001\u5B9A\u7FA9\u4EE5\u53CA\u5176\u7528\u9014\u3002\u6CE8\u610F\u76E1\u91CF\u6311\u9078\u9069\u7576\u7684\u56DB\u5927\u5206\u985E\uFF0C\u771F\u7684\u4E0D\u884C\u518D\u9078 99_Uncategorized\u3002
</note>
<note title="\u53E6\u4E00\u500B\u6846\u67B6" tags="#tag3" category="10_Work_&_Management">
...
</note>
</atomic-notes>
`;
var ArticleProcessorEngine = class {
  constructor(app, apiClient, temperature) {
    this.app = app;
    this.apiClient = apiClient;
    this.temperature = temperature;
  }
  async processFile(file) {
    try {
      const content = await this.app.vault.read(file);
      const urlMatch = content.match(/URL:\s*(https?:\/\/[^\s]+)/i) || content.match(/Source:\s*(https?:\/\/[^\s]+)/i);
      const sourceUrl = urlMatch ? urlMatch[1] : "";
      const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
      const systemPrompt = ARTICLE_PROCESSOR_PROMPT.replace(/\{CAPTURED_DATE\}/g, today).replace(/\{SOURCE_URL\}/g, sourceUrl || "[\u586B\u5BEB\u539F\u6587\u7DB2\u5740\uFF0C\u82E5\u7121\u5247\u7559\u7A7A]");
      new import_obsidian4.Notice(`Processing article "${file.basename}"... This might take a while.`);
      const rawResponse = await this.apiClient.prompt(
        systemPrompt,
        content,
        this.temperature
      );
      let finalMarkdown = rawResponse.trim();
      finalMarkdown = finalMarkdown.replace(/^```markdown\n/i, "");
      finalMarkdown = finalMarkdown.replace(/\n```$/, "");
      finalMarkdown = finalMarkdown.replace(/^```yaml\n/i, "");
      finalMarkdown = finalMarkdown.replace(/---\n```\n/g, "---\n");
      finalMarkdown = finalMarkdown.replace(/^```\n/i, "");
      finalMarkdown = finalMarkdown.trim();
      if (!finalMarkdown.startsWith("---")) {
        const match = finalMarkdown.match(/---\n[\s\S]*?\n---/);
        if (match) {
          finalMarkdown = finalMarkdown.substring(match.index);
        }
      }
      let finalCategory = "99_Uncategorized";
      const catMatch = finalMarkdown.match(/category:\s*(.+)/i);
      if (catMatch) {
        finalCategory = catMatch[1].trim().replace(/^["'\[\]]+|["'\[\]]+$/g, "");
        if (!PILLARS3.includes(finalCategory)) {
          finalCategory = "99_Uncategorized";
        }
      }
      const atomicRegex = /<atomic-notes>([\s\S]*?)<\/atomic-notes>/i;
      const atomicMatch = finalMarkdown.match(atomicRegex);
      if (atomicMatch) {
        finalMarkdown = finalMarkdown.replace(atomicRegex, "").trim();
        const noteBlock = atomicMatch[1];
        const noteRegex = /<note\s+title="([^"]+)"(?:[^>]*)?>([\s\S]*?)<\/note>/gi;
        const tagsRegex = /tags="([^"]+)"/i;
        const catAttrRegex = /category="([^"]+)"/i;
        let nMatch;
        while ((nMatch = noteRegex.exec(noteBlock)) !== null) {
          const fullTagStr = nMatch[0];
          const title = nMatch[1].trim();
          const tagsAttrMatch = fullTagStr.match(tagsRegex);
          const tagsStr = tagsAttrMatch ? tagsAttrMatch[1].trim() : "";
          const catAttrMatch = fullTagStr.match(catAttrRegex);
          let noteCategory = catAttrMatch ? catAttrMatch[1].trim() : finalCategory;
          if (!PILLARS3.includes(noteCategory)) {
            noteCategory = "99_Uncategorized";
          }
          const content2 = nMatch[2].trim();
          const tagsArr = tagsStr.split(/\s+/).filter(Boolean);
          try {
            await this.createAtomicNote(title, content2, tagsArr, noteCategory, file.basename);
          } catch (err) {
            console.error("[ArticleProcessorEngine] Failed atomic note:", title, err);
          }
        }
      }
      const llmFmMatch = finalMarkdown.match(/^---\n([\s\S]*?)\n---/);
      const llmFmString = llmFmMatch ? llmFmMatch[1] : "";
      const finalBody = finalMarkdown.replace(/^---\n[\s\S]*?\n---\n*/, "").trim();
      const originalFmMatch = content.match(/^---\n([\s\S]*?)\n---/);
      const originalFmFull = originalFmMatch ? originalFmMatch[0] + "\n" : "";
      const imageRegex = /<img\s+[^>]*src="[^"]+"[^>]*>|!\[.*?\]\(.*?\)|\!\[\[.*?\]\]/gi;
      const imagesMatch = content.match(imageRegex);
      const uniqueImages = imagesMatch ? Array.from(new Set(imagesMatch)) : [];
      let imagesSection = "";
      if (uniqueImages.length > 0) {
        imagesSection = "\n\n## \u539F\u59CB\u9644\u5716 (Saved Images)\n" + uniqueImages.join("\n\n") + "\n";
      }
      await this.app.vault.modify(file, originalFmFull + finalBody + imagesSection);
      await this.app.fileManager.processFrontMatter(file, (fm) => {
        fm["type"] = "reference";
        fm["captured"] = today;
        if (sourceUrl) fm["source"] = sourceUrl;
        if (finalCategory) fm["category"] = finalCategory;
        const tagsMatch = llmFmString.match(/tags:\s*(.+)/i);
        if (tagsMatch) {
          const rawTags = tagsMatch[1].replace(/[\[\]"',]/g, " ").split(/\s+/).filter((t) => t.length > 0 && t !== "#web-clippings").map((t) => t.replace(/^#/, ""));
          const existingTags = Array.isArray(fm["tags"]) ? fm["tags"].map((t) => t.replace(/^#/, "")) : [];
          fm["tags"] = Array.from(/* @__PURE__ */ new Set([...existingTags, ...rawTags, "web-clippings"]));
        }
      });
      if (finalCategory) {
        await this.moveFileToCategory(file, finalCategory);
      }
    } catch (err) {
      console.error("[ArticleProcessorEngine] Error processing file:", err);
      throw err;
    }
  }
  async createAtomicNote(title, content, tags, category, sourceName) {
    let safeTitle = title.replace(/[\\/:"*?<>|#^\[\]]/g, "").trim() || "Atomic Note";
    const destFolder = (0, import_obsidian4.normalizePath)(category);
    const abstractFolder = this.app.vault.getAbstractFileByPath(destFolder);
    if (!abstractFolder) {
      await this.app.vault.createFolder(destFolder);
    }
    let attempt = 0;
    let finalPath = (0, import_obsidian4.normalizePath)(`${category}/${safeTitle}.md`);
    while (this.app.vault.getAbstractFileByPath(finalPath)) {
      attempt++;
      finalPath = (0, import_obsidian4.normalizePath)(`${category}/${safeTitle} ${attempt}.md`);
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const tagsStr = tags.length > 0 ? `tags:
  - ${tags.map((t) => t.replace(/^#/, "")).join("\n  - ")}` : "tags: []";
    const fullContent = `---
type: atomic-note
category: ${category}
${tagsStr}
created: ${today}
---
\u4F86\u6E90\u7B46\u8A18\uFF1A[[${sourceName}]]

# ${safeTitle}

${content}
`;
    await this.app.vault.create(finalPath, fullContent);
  }
  async moveFileToCategory(file, category) {
    const destFolder = (0, import_obsidian4.normalizePath)(category);
    const abstractFolder = this.app.vault.getAbstractFileByPath(destFolder);
    if (!abstractFolder) {
      await this.app.vault.createFolder(destFolder);
    }
    const newPath = (0, import_obsidian4.normalizePath)(`${category}/${file.name}`);
    await this.app.vault.rename(file, newPath);
  }
};

// src/writer.ts
var import_obsidian5 = require("obsidian");
var SUGGEST_PROMPT = `\u4F60\u662F\u4E00\u500B\u77E5\u8B58\u5EAB\u6AA2\u7D22\u4EE3\u7406\u3002\u8ACB\u95B1\u8B80\u4F7F\u7528\u8005\u7684\u300C\u5BEB\u4F5C\u76EE\u6A19\u300D\uFF0C\u4E26\u5F9E\u4E0B\u65B9\u63D0\u4F9B\u7684\u300C\u53EF\u7528\u7B46\u8A18\u6A19\u984C\u6E05\u55AE\u300D\u4E2D\uFF0C\u6311\u9078\u51FA\u6700\u76F8\u95DC\u3001\u6700\u80FD\u652F\u63F4\u6B64\u76EE\u6A19\u7684 5 \u5230 10 \u7BC7\u7B46\u8A18\u3002
\u56B4\u683C\u8981\u6C42\uFF1A
1. \u53EA\u80FD\u6311\u9078\u6E05\u55AE\u300C\u53EF\u7528\u7B46\u8A18\u6A19\u984C\u6E05\u55AE\u300D\u4E2D\u5BE6\u969B\u5B58\u5728\u7684\u7B46\u8A18\uFF0C\u7D55\u4E0D\u80FD\u81EA\u5DF1\u767C\u660E\u540D\u7A31\u3002
2. \u8F38\u51FA\u7684\u683C\u5F0F\u53EA\u80FD\u662F\u5217\u8868\u4E26\u52A0\u4E0A\u96D9\u5C64\u4E2D\u62EC\u865F\uFF0C\u4E0D\u5F97\u8F38\u51FA\u4EFB\u4F55\u524D\u5F8C\u6587\u6216\u662F\u8AAA\u660E\u5EE2\u8A71\u3002\u4F8B\u5982\uFF1A
- [[\u7B46\u8A18\u540D\u7A31A]]
- [[\u7B46\u8A18\u540D\u7A31B]]`;
var STANDUP_PROMPT = `\u4F60\u662F\u4E00\u500B\u5C08\u696D\u7684\u5BEB\u4F5C\u4EE3\u7406\u3002\u4F60\u7684\u4EFB\u52D9\u662F\u57F7\u884C\u300C\u6668\u9593\u7C21\u5831\u300D\uFF08Standup\uFF09\u3002
\u8ACB\u95B1\u8B80\u4EE5\u4E0B\u904E\u53BB\u4E09\u5929\u5167\u7684\u7B46\u8A18\u6216\u662F\u8207\u76EE\u524D\u5BEB\u4F5C\u76EE\u6A19\u76F8\u95DC\u7684\u5167\u5BB9\uFF0C\u4E26\u81EA\u52D5\u751F\u6210\u8207\u7576\u524D\u5275\u4F5C\u4EFB\u52D9\uFF08\u53C3\u898B plan.md \u7684\u76EE\u6A19\uFF09\u76F8\u95DC\u7684\u80CC\u666F\u8CC7\u8A0A\u7E3D\u7D50\u3002
\u8ACB\u627E\u51FA\u53EF\u7528\u7684\u6D1E\u898B\u3001\u4E8B\u5BE6\u8207\u9023\u7D50\uFF0C\u8B93\u5BEB\u4F5C\u8005\u80FD\u76F4\u63A5\u5229\u7528\u3002
\u8F38\u51FA\u683C\u5F0F\uFF1A
## \u6668\u9593\u7C21\u5831\uFF1A\u80CC\u666F\u8CC7\u8A0A\u7E3D\u7D50
- \u7E3D\u7D50\u689D\u76EE\uFF0C\u4E26\u9644\u5E36\u539F\u6587\u9023\u7D50 [[\u7B46\u8A18\u540D\u7A31]]`;
var DRAFTING_PROMPT = `\u4F60\u662F\u4E00\u500B\u5C08\u696D\u7684\u5167\u5BB9\u5275\u4F5C\u8005\u3002\u8ACB\u6839\u64DA\u4F7F\u7528\u8005\u63D0\u4F9B\u7684 \`plan.md\`\uFF08\u5305\u542B\u76EE\u6A19\u3001\u67B6\u69CB\u8207\u80CC\u666F\u8CC7\u8A0A\uFF09\u4F86\u8349\u64EC\u4E00\u7BC7\u6587\u7AE0\u3002
\u56B4\u683C\u8981\u6C42\uFF1A
1. \u884D\u751F\u5F0F\u5BEB\u4F5C\uFF1A\u5728\u751F\u6210\u65B0\u5167\u5BB9\u6642\uFF0C\u5FC5\u9808\u9644\u5E36\u4F86\u6E90\u7B46\u8A18\u7684\u539F\u6587\u5F15\u7528\u8207\u9023\u7D50\uFF08Quotes & Links\uFF09\uFF0C\u78BA\u4FDD\u65B0\u6587\u7AE0\u7684\u8AD6\u9EDE\u6709\u8DE1\u53EF\u5FAA\uFF0C\u96A8\u6642\u53EF\u4EE5\u56DE\u6EAF\u4E8B\u5BE6\u3002\u8ACB\u5728\u884C\u6587\u4E2D\u4F7F\u7528 \`[[\u7B46\u8A18\u540D\u7A31]]\` \u7684\u8A9E\u6CD5\u3002
2. \u958B\u982D\u5FC5\u9808\u5305\u542B\u6A19\u6E96 YAML \u5C6C\u6027\uFF08\u5305\u542B type: draft, category, tags\uFF09\u3002
3. \u8A9E\u6C23\u5C08\u696D\u3001\u6D41\u66A2\u3002`;
var SWEEP_PROMPT = `\u4F60\u662F\u4E00\u500B\u56B4\u8B39\u7684\u5BEB\u4F5C\u52A9\u7406\u3002\u8ACB\u57F7\u884C\u300C\u6383\u9664\uFF08Sweep\uFF09\u300D\u8207\u300C\u5BE9\u6838\u300D\u4EFB\u52D9\u3002
\u95B1\u8B80\u76EE\u524D\u7684\u8349\u7A3F\uFF0C\u5B8C\u6210\u4EE5\u4E0B\u6AA2\u67E5\u8207\u5EFA\u8B70\uFF1A
1. \u662F\u5426\u6709\u907A\u6F0F\u7684YAML\u5C6C\u6027\uFF1F
2. \u662F\u5426\u5177\u5099\u81F3\u5C11\u4E00\u500B\u6307\u5411\u73FE\u6709\u7B46\u8A18\u7684\u9023\u7D50 \`[[ ]]\`\uFF1F
3. \u5F9E\u8349\u7A3F\u5167\u5BB9\u4E2D\u5C0B\u627E\u53EF\u80FD\u7684\u908F\u8F2F\u76F2\u5340\uFF0C\u5EFA\u8B70\u662F\u5426\u9700\u8981\u88DC\u5145\u5176\u4ED6\u4EBA\u7269\u8A8C\uFF08People notes\uFF09\u6216\u5C08\u6848\u80CC\u666F\u3002
\u8ACB\u4EE5\u7C21\u6F54\u7684\u5217\u8868\u56DE\u5831\u4F60\u7684\u5BE9\u6838\u8207 Sweep \u7D50\u679C\u3002`;
var TopicInputModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.topic = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u8ACB\u63CF\u8FF0\u4F60\u60F3\u5BEB\u4EC0\u9EBC\uFF1F (\u60C5\u5883\u5DE5\u7A0B)" });
    contentEl.createEl("p", { text: "\u8ACB\u8F38\u5165\u9019\u7BC7\u6587\u7AE0\u7684\u4E3B\u984C\u65B9\u5411\u6216\u60F3\u63A2\u8A0E\u7684\u554F\u984C\u3002Agent \u5C07\u6839\u64DA\u60A8\u7684\u76EE\u6A19\uFF0C\u6383\u63CF\u6574\u500B Vault \u4E26\u70BA\u60A8\u627E\u51FA\u73FE\u6709\u7684\u76F8\u95DC\u5EAB\u5B58\u7B46\u8A18\u505A\u70BA\u53C3\u8003\uFF01" });
    new import_obsidian5.Setting(contentEl).setName("\u5BEB\u4F5C\u76EE\u6A19\u8207\u95DC\u9375\u5B57").addTextArea((text) => {
      text.inputEl.setAttr("rows", 4);
      text.inputEl.style.width = "100%";
      text.onChange((value) => {
        this.topic = value;
      });
    });
    new import_obsidian5.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("\u81EA\u52D5\u68C0\u7D22\u8207\u5EFA\u7ACB\u8A08\u756B").setCta().onClick(() => {
        this.close();
        this.onSubmit(this.topic);
      })
    );
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var WriterEngine = class {
  constructor(app, apiClient, temperature) {
    this.app = app;
    this.apiClient = apiClient;
    this.temperature = temperature;
  }
  /**
   * 1. Initialize Writing Project
   * 建立一個新的專案資料夾與 plan.md
   */
  async initProject(projectName, objective) {
    new import_obsidian5.Notice("Agentic Reasoning: Searching your vault titles...");
    try {
      const allTitles = this.app.vault.getMarkdownFiles().map((f) => f.basename).filter((n) => !n.includes("Atomic Note") && n !== "plan" && n !== "draft");
      const promptInput = `### \u5BEB\u4F5C\u76EE\u6A19
${objective}

### \u53EF\u7528\u7B46\u8A18\u6A19\u984C\u6E05\u55AE
${allTitles.join("\n")}`;
      const suggestedLinks = await this.apiClient.prompt(
        SUGGEST_PROMPT,
        promptInput,
        this.temperature
      );
      const safeName = projectName.replace(/[\\/:"*?<>|#^\[\]]/g, "").trim() || "New_Project";
      const destFolder = (0, import_obsidian5.normalizePath)(`99_Uncategorized/${safeName}`);
      const abstractFolder = this.app.vault.getAbstractFileByPath(destFolder);
      if (!abstractFolder) {
        await this.app.vault.createFolder(destFolder);
      }
      const planPath = (0, import_obsidian5.normalizePath)(`${destFolder}/plan.md`);
      if (!this.app.vault.getAbstractFileByPath(planPath)) {
        const planTemplate = `---
type: plan
project: ${safeName}
status: planning
---
# \u5BEB\u4F5C\u8A08\u756B\uFF1A${safeName}

## \u76EE\u6A19 (Objective)
${objective}

## \u67B6\u69CB (Structure)
1. \u524D\u8A00
2. \u6838\u5FC3\u89C0\u9EDE
3. \u7D50\u8AD6

## \u9700\u8981\u5F15\u7528\u7684\u65E2\u6709\u7B46\u8A18 (Required Notes)
${suggestedLinks.trim()}

## \u60C5\u5883\u5DE5\u7A0B\uFF1A\u6668\u9593\u7C21\u5831\u80CC\u666F\u5340 (Context)
[\u900F\u904E Standup \u6307\u4EE4\u81EA\u52D5\u751F\u6210\u5340\u584A]
`;
        const file = await this.app.vault.create(planPath, planTemplate);
        new import_obsidian5.Notice(`Initialized Writing Project: ${safeName}`);
        await this.app.workspace.getLeaf(false).openFile(file);
      } else {
        new import_obsidian5.Notice("Project already exists!");
      }
    } catch (err) {
      console.error("[WriterEngine] Init failed:", err);
      new import_obsidian5.Notice(`Initialization failed: ${err.message}`);
    }
  }
  /**
   * 2. Standup (Retrieve recent context)
   */
  async generateStandup(planFile) {
    new import_obsidian5.Notice("Running Agentic Standup (Gathering Context via Graph & Time)...");
    try {
      const planContent = await this.app.vault.read(planFile);
      const candidateFiles = /* @__PURE__ */ new Set();
      const explicitLinkRegex = /\[\[(.*?)\]\]/g;
      let match;
      while ((match = explicitLinkRegex.exec(planContent)) !== null) {
        const linkName = match[1].split("|")[0].trim();
        const targetFile = this.app.metadataCache.getFirstLinkpathDest(linkName, planFile.path);
        if (targetFile && targetFile instanceof import_obsidian5.TFile) {
          candidateFiles.add(targetFile);
          const resolved = this.app.metadataCache.resolvedLinks;
          if (resolved[targetFile.path]) {
            for (const outlink in resolved[targetFile.path]) {
              const outF = this.app.vault.getAbstractFileByPath(outlink);
              if (outF && outF instanceof import_obsidian5.TFile) candidateFiles.add(outF);
            }
          }
          for (const sourcePath in resolved) {
            if (resolved[sourcePath][targetFile.path]) {
              const bgFile = this.app.vault.getAbstractFileByPath(sourcePath);
              if (bgFile && bgFile instanceof import_obsidian5.TFile) candidateFiles.add(bgFile);
            }
          }
        }
      }
      const allFiles = this.app.vault.getMarkdownFiles();
      const threeDaysAgo = Date.now() - 3 * 24 * 60 * 60 * 1e3;
      for (const f of allFiles) {
        if (f.stat.mtime >= threeDaysAgo && f.path !== planFile.path) {
          candidateFiles.add(f);
        }
      }
      const candidatesArr = Array.from(candidateFiles).filter((f) => f.path !== planFile.path).sort((a, b) => b.stat.mtime - a.stat.mtime);
      let notesBundle = "";
      for (const f of candidatesArr.slice(0, 15)) {
        const text = await this.app.vault.read(f);
        notesBundle += `

--- FILE: [[${f.basename}]] ---
${text.substring(0, 600)}`;
      }
      if (notesBundle.length === 0) {
        new import_obsidian5.Notice("No related graph or temporal notes found for standup.");
        return;
      }
      const userPrompt = `### \u5BEB\u4F5C\u8A08\u756B\u76EE\u6A19
${planContent}

### \u8FD1\u671F\u7B46\u8A18\u5EAB\u5167\u5BB9
${notesBundle}`;
      const response = await this.apiClient.prompt(
        STANDUP_PROMPT,
        userPrompt,
        this.temperature
      );
      const mergedContent = planContent + "\n\n" + response.trim();
      await this.app.vault.modify(planFile, mergedContent);
      new import_obsidian5.Notice("Standup completed! Context added to plan.md");
    } catch (err) {
      console.error("[WriterEngine] Standup failed:", err);
      new import_obsidian5.Notice(`Standup failed: ${err.message}`);
    }
  }
  /**
   * 3. Draft Article based on Plan
   */
  async draftArticle(planFile) {
    var _a;
    new import_obsidian5.Notice("Drafting article... This will take a while.");
    try {
      const planContent = await this.app.vault.read(planFile);
      const response = await this.apiClient.prompt(
        DRAFTING_PROMPT,
        `\u8ACB\u6839\u64DA\u6B64\u5BEB\u4F5C\u8A08\u756B\u8207\u80CC\u666F\u958B\u59CB\u64B0\u5BEB\uFF1A

${planContent}`,
        Math.max(0.6, this.temperature + 0.3)
        // Slightly more creative
      );
      let cleanDraft = response.trim();
      if (cleanDraft.startsWith("```markdown")) {
        cleanDraft = cleanDraft.replace(/^```markdown\n/, "").replace(/\n```$/, "");
      }
      const draftPath = (0, import_obsidian5.normalizePath)(`${(_a = planFile.parent) == null ? void 0 : _a.path}/draft.md`);
      const fileExisted = this.app.vault.getAbstractFileByPath(draftPath);
      let draftFile;
      if (fileExisted && fileExisted instanceof import_obsidian5.TFile) {
        await this.app.vault.modify(fileExisted, cleanDraft);
        draftFile = fileExisted;
      } else {
        draftFile = await this.app.vault.create(draftPath, cleanDraft);
      }
      new import_obsidian5.Notice("Draft generated successfully.");
      await this.app.workspace.getLeaf(false).openFile(draftFile);
    } catch (err) {
      console.error("[WriterEngine] Drafting failed:", err);
      new import_obsidian5.Notice(`Drafting failed: ${err.message}`);
    }
  }
  /**
   * 4. Sweep / Hook Verification
   */
  async sweepDraft(draftFile) {
    new import_obsidian5.Notice("Running Sweep & Verification on draft...");
    try {
      const draftContent = await this.app.vault.read(draftFile);
      const response = await this.apiClient.prompt(
        SWEEP_PROMPT,
        draftContent,
        this.temperature
      );
      const appended = `

%% SWEEP REVIEW %%
${response.replace(/^/gm, "%% ")}`;
      await this.app.vault.modify(draftFile, draftContent + appended);
      new import_obsidian5.Notice("Sweep completed. Check the bottom of your draft for suggestions.");
    } catch (err) {
      console.error("[WriterEngine] Sweep failed:", err);
      new import_obsidian5.Notice(`Sweep failed: ${err.message}`);
    }
  }
};

// src/settings.ts
var import_obsidian6 = require("obsidian");
var DEFAULT_SETTINGS = {
  apiEndpoint: "http://localhost:11434",
  defaultModel: "llama3",
  inputFolder: "Daily Notes",
  outputFolder: "Insights",
  maxFilesToProcess: 20,
  classificationTemperature: 0.2,
  aggregationTemperature: 0.5,
  refinementTemperature: 0.3
};
var LocalAgentSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "Obsidian Local Agent" });
    containerEl.createEl("p", {
      text: "Configure your local LLM connection and folder paths for automated knowledge management.",
      cls: "setting-item-description"
    });
    containerEl.createEl("h2", { text: "API Connection" });
    new import_obsidian6.Setting(containerEl).setName("API Endpoint").setDesc(
      "Base URL of your local LLM server (Ollama, LM Studio, etc.). Example: http://localhost:11434"
    ).addText(
      (text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
        this.plugin.settings.apiEndpoint = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Default Model").setDesc(
      "The model identifier to use for inference (e.g. llama3, mistral, deepseek-r1)."
    ).addText(
      (text) => text.setPlaceholder("llama3").setValue(this.plugin.settings.defaultModel).onChange(async (value) => {
        this.plugin.settings.defaultModel = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Test Connection").setDesc("Verify that the local LLM server is reachable.").addButton(
      (button) => button.setButtonText("Ping Server").onClick(async () => {
        button.setDisabled(true);
        button.setButtonText("Testing...");
        try {
          const ok = await this.plugin.apiClient.ping();
          if (ok) {
            new import_obsidian6.Notice("Connection successful \u2014 LLM server is reachable.");
          } else {
            new import_obsidian6.Notice(
              "Connection failed \u2014 could not reach the LLM server. Check the endpoint URL."
            );
          }
        } catch (err) {
          new import_obsidian6.Notice(`Connection error: ${err.message}`);
        } finally {
          button.setDisabled(false);
          button.setButtonText("Ping Server");
        }
      })
    );
    containerEl.createEl("h2", { text: "Folder Configuration" });
    new import_obsidian6.Setting(containerEl).setName("Input Folder").setDesc(
      "Vault-relative path to the folder containing source notes for aggregation (e.g. Daily Notes)."
    ).addText(
      (text) => text.setPlaceholder("Daily Notes").setValue(this.plugin.settings.inputFolder).onChange(async (value) => {
        this.plugin.settings.inputFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Output Folder").setDesc(
      "Vault-relative path to the folder where Insight Reports will be created."
    ).addText(
      (text) => text.setPlaceholder("Insights").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
        this.plugin.settings.outputFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "Processing Options" });
    new import_obsidian6.Setting(containerEl).setName("Max Files to Process").setDesc(
      "Maximum number of recent notes to include in a single Map-Reduce aggregation run."
    ).addSlider(
      (slider) => slider.setLimits(1, 100, 1).setValue(this.plugin.settings.maxFilesToProcess).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxFilesToProcess = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Classification Temperature").setDesc(
      "LLM temperature for tagging/classification (lower = more deterministic). Range: 0.0 - 1.0."
    ).addSlider(
      (slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.classificationTemperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.classificationTemperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Aggregation Temperature").setDesc(
      "LLM temperature for summary/aggregation tasks (higher = more creative). Range: 0.0 - 1.0."
    ).addSlider(
      (slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.aggregationTemperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.aggregationTemperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Refinement Temperature").setDesc(
      "LLM temperature for the combined Summary/Highlight/Atomize Refiner task. Default 0.3."
    ).addSlider(
      (slider) => slider.setLimits(0, 1, 0.05).setValue(this.plugin.settings.refinementTemperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.refinementTemperature = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var MAP_SUMMARY_SYSTEM_PROMPT = `You are a concise summariser. Read the following note and produce exactly ONE sentence that captures the core idea or theme. Do not add any preamble \u2014 respond with the single sentence only.`;
var REDUCE_INSIGHT_SYSTEM_PROMPT = `You are an analytical research assistant. You will receive a numbered list of one-sentence summaries from different notes written over a period of time.

Your task:
1. Identify recurring themes, patterns, or emerging connections across the summaries.
2. Highlight any contradictions or evolving viewpoints.
3. Suggest actionable next steps or open questions.

Format your response as a well-structured markdown report with the following sections:
## Recurring Themes
## Key Connections
## Contradictions & Tensions
## Open Questions & Next Steps

Be insightful and specific. Reference summary numbers (e.g. "[3]") when citing evidence.`;
var LocalAgentPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.apiClient = new LocalLLMClient({
      endpoint: DEFAULT_SETTINGS.apiEndpoint,
      model: DEFAULT_SETTINGS.defaultModel
    });
    this.statusBarEl = null;
    this.isProcessing = false;
    this.cancelProcessing = false;
  }
  // ---- Lifecycle ----------------------------------------------------------
  async onload() {
    await this.loadSettings();
    this.apiClient.setEndpoint(this.settings.apiEndpoint);
    this.apiClient.setModel(this.settings.defaultModel);
    this.statusBarEl = this.addStatusBarItem();
    this.setStatusBarText("");
    this.addSettingTab(new LocalAgentSettingTab(this.app, this));
    const ribbonIconEl = this.addRibbonIcon("bot", "Start Classification (Active Note)", (evt) => {
      this.classifyActiveNote();
    });
    ribbonIconEl.addClass("local-agent-ribbon-class");
    const refinerIconEl = this.addRibbonIcon("sparkles", "Refine Active Note (Summary, Highlight, Atomize)", (evt) => {
      this.refineActiveNote();
    });
    refinerIconEl.addClass("local-agent-refine-class");
    const articleIconEl = this.addRibbonIcon("book-open", "Process Inbox Articles (Batch Process)", (evt) => {
      this.processInboxArticles();
    });
    articleIconEl.addClass("local-agent-article-class");
    this.addCommand({
      id: "classify-active-note",
      name: "Classify Active Note (Tags & Category)",
      callback: () => this.classifyActiveNote()
    });
    this.addCommand({
      id: "run-map-reduce",
      name: "Run Map-Reduce Aggregation on Input Folder",
      callback: () => this.runMapReduce()
    });
    this.addCommand({
      id: "refine-active-note",
      name: "Refine Active Note (Summary, Highlight, Atomize, Classify)",
      callback: () => this.refineActiveNote()
    });
    this.addCommand({
      id: "process-inbox-articles",
      name: "Process Inbox Articles (Batch Format with Atomization)",
      callback: () => this.processInboxArticles()
    });
    this.addCommand({
      id: "cancel-local-agent-processing",
      name: "Cancel Current Processing Task",
      callback: () => {
        if (this.isProcessing) {
          this.cancelProcessing = true;
          new import_obsidian7.Notice("Cancelling background tasks...");
          this.setStatusBarText("Cancelling...");
        } else {
          new import_obsidian7.Notice("No tasks are currently running.");
        }
      }
    });
    this.addCommand({
      id: "writer-init-project",
      name: "Writer: Initialize Writing Project (plan.md)",
      callback: () => this.handleWriterInit()
    });
    this.addCommand({
      id: "writer-om-standup",
      name: "Writer: Morning Standup (Gather Context from Last 3 Days)",
      callback: () => this.handleWriterAction("standup")
    });
    this.addCommand({
      id: "writer-draft-article",
      name: "Writer: Draft Article (from plan.md)",
      callback: () => this.handleWriterAction("draft")
    });
    this.addCommand({
      id: "writer-sweep-draft",
      name: "Writer: Sweep & Feedback (Review Draft with Knowledge Base)",
      callback: () => this.handleWriterAction("sweep")
    });
  }
  onunload() {
    this.setStatusBarText("");
  }
  // ---- Settings persistence -----------------------------------------------
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.apiClient.setEndpoint(this.settings.apiEndpoint);
    this.apiClient.setModel(this.settings.defaultModel);
  }
  // ---- Status bar helper --------------------------------------------------
  setStatusBarText(text) {
    if (this.statusBarEl) {
      this.statusBarEl.setText(text);
    }
  }
  // ========================================================================
  // MODULE 2 — Structured Classification Engine
  // ========================================================================
  /**
   * Reads the currently active markdown file and routes it to the ClassificationEngine
   * to determine its pillar and tag it appropriately.
   */
  async classifyActiveNote() {
    if (this.isProcessing) {
      new import_obsidian7.Notice("Local Agent is already processing. Please wait.");
      return;
    }
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
    if (!activeView || !activeView.file) {
      new import_obsidian7.Notice("No active markdown file to classify.");
      return;
    }
    const file = activeView.file;
    this.isProcessing = true;
    this.setStatusBarText("Classifying via ClassificationEngine...");
    try {
      const engine = new ClassificationEngine(
        this.app,
        this.apiClient,
        this.settings.classificationTemperature
      );
      await engine.classifyFile(file);
    } finally {
      this.isProcessing = false;
      this.setStatusBarText("");
    }
  }
  // ========================================================================
  // MODULE 3 — Map-Reduce Aggregation Engine
  // ========================================================================
  // ========================================================================
  // MODULE 4 — Note Refiner Engine
  // ========================================================================
  async refineActiveNote() {
    if (this.isProcessing) {
      new import_obsidian7.Notice("Local Agent is already processing. Please wait.");
      return;
    }
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
    if (!activeView || !activeView.file) {
      new import_obsidian7.Notice("No active markdown file to refine.");
      return;
    }
    const file = activeView.file;
    this.isProcessing = true;
    this.setStatusBarText("Refining via NoteRefinerEngine...");
    try {
      const engine = new NoteRefinerEngine(
        this.app,
        this.apiClient,
        this.settings.refinementTemperature
      );
      await engine.refineFile(file);
    } catch (err) {
      console.error("[Local Agent] Refiner error:", err);
      new import_obsidian7.Notice(`Refinement failed: ${err.message}`);
    } finally {
      this.isProcessing = false;
      this.setStatusBarText("");
    }
  }
  // ========================================================================
  // MODULE 5 — Article Processor Engine
  // ========================================================================
  async processInboxArticles() {
    if (this.isProcessing) {
      new import_obsidian7.Notice("Local Agent is already processing. Please wait or use Cancel command.");
      return;
    }
    this.isProcessing = true;
    this.cancelProcessing = false;
    this.setStatusBarText("Batch Processing Articles in 00_Inbox...");
    try {
      const files = await this.getRecentMarkdownFiles("00_Inbox", 999);
      if (files.length === 0) {
        new import_obsidian7.Notice("No markdown files found in '00_Inbox'.");
        return;
      }
      new import_obsidian7.Notice(`Found ${files.length} notes in 00_Inbox. Starting batch process...`);
      const engine = new ArticleProcessorEngine(
        this.app,
        this.apiClient,
        this.settings.refinementTemperature
      );
      let processedCount = 0;
      for (let i = 0; i < files.length; i++) {
        if (this.cancelProcessing) {
          new import_obsidian7.Notice("Batch processing was cancelled by user.");
          break;
        }
        const file = files[i];
        this.setStatusBarText(`Processing Article ${i + 1}/${files.length}: ${file.basename}...`);
        try {
          const content = await this.app.vault.read(file);
          if (content.includes("type: atomic-note") || content.includes("type: reference")) {
            console.log(`[Local Agent] Skipping ${file.basename}: already processed or is an atomic note.`);
            continue;
          }
          await engine.processFile(file);
          processedCount++;
          new import_obsidian7.Notice(`Processed (${processedCount}/${files.length}): ${file.basename}`);
        } catch (err) {
          console.error(`[Local Agent] Failed to process ${file.basename}:`, err);
        }
      }
      new import_obsidian7.Notice(`Batch Processing completed or stopped. Processed ${processedCount}/${files.length} notes.`);
    } catch (err) {
      console.error("[Local Agent] Batch Article Processor error:", err);
      new import_obsidian7.Notice(`Batch Processing failed: ${err.message}`);
    } finally {
      this.isProcessing = false;
      this.cancelProcessing = false;
      this.setStatusBarText("");
    }
  }
  // ========================================================================
  // MODULE 6 — Creative Writing Engine
  // ========================================================================
  async handleWriterInit() {
    new TopicInputModal(this.app, async (topic) => {
      if (!topic) {
        new import_obsidian7.Notice("\u672A\u8F38\u5165\u5BEB\u4F5C\u76EE\u6A19\uFF0C\u5DF2\u53D6\u6D88\u8A08\u756B\u5EFA\u7ACB\u3002");
        return;
      }
      const engine = new WriterEngine(this.app, this.apiClient, this.settings.refinementTemperature);
      const projectId = "Draft_" + Date.now().toString().slice(-6);
      await engine.initProject(projectId, topic);
    }).open();
  }
  async handleWriterAction(action) {
    if (this.isProcessing) {
      new import_obsidian7.Notice("Local Agent is already processing. Please wait or use Cancel command.");
      return;
    }
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
    if (!activeView || !activeView.file) {
      new import_obsidian7.Notice("Please open a plan.md or draft.md to perform this action.");
      return;
    }
    this.isProcessing = true;
    this.cancelProcessing = false;
    this.setStatusBarText(`Writer executing: ${action}...`);
    try {
      const engine = new WriterEngine(this.app, this.apiClient, this.settings.refinementTemperature);
      if (action === "standup") {
        await engine.generateStandup(activeView.file);
      } else if (action === "draft") {
        await engine.draftArticle(activeView.file);
      } else if (action === "sweep") {
        await engine.sweepDraft(activeView.file);
      }
    } catch (err) {
      console.error(`[Local Agent] Writer error (${action}):`, err);
    } finally {
      this.isProcessing = false;
      this.cancelProcessing = false;
      this.setStatusBarText("");
    }
  }
  /**
   * Orchestrates the full map-reduce pipeline:
   *   1. Fetch recent markdown files from the input folder.
   *   2. MAP — Summarise each note into one sentence via the LLM.
   *   3. REDUCE — Feed all summaries to the LLM for a global insight report.
   *   4. Write the report as a new markdown file in the output folder.
   */
  async runMapReduce() {
    if (this.isProcessing) {
      new import_obsidian7.Notice("Local Agent is already processing. Please wait.");
      return;
    }
    this.isProcessing = true;
    this.setStatusBarText("Preparing aggregation...");
    try {
      const files = await this.getRecentMarkdownFiles(
        this.settings.inputFolder,
        this.settings.maxFilesToProcess
      );
      if (files.length === 0) {
        new import_obsidian7.Notice(
          `No markdown files found in "${this.settings.inputFolder}".`
        );
        return;
      }
      new import_obsidian7.Notice(
        `Starting Map-Reduce on ${files.length} note(s) from "${this.settings.inputFolder}"...`
      );
      const summaries = [];
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        this.setStatusBarText(
          `Mapping note ${i + 1}/${files.length}...`
        );
        try {
          const content = await this.app.vault.read(file);
          const body = this.stripFrontmatter(content);
          if (body.trim().length < 20) {
            summaries.push({
              index: i + 1,
              name: file.basename,
              summary: "(Note was too short to summarise.)"
            });
            continue;
          }
          const summary = await this.apiClient.prompt(
            MAP_SUMMARY_SYSTEM_PROMPT,
            body,
            this.settings.aggregationTemperature
          );
          summaries.push({
            index: i + 1,
            name: file.basename,
            summary: summary.trim()
          });
        } catch (err) {
          console.error(
            `[Local Agent] Map error on "${file.basename}":`,
            err
          );
          summaries.push({
            index: i + 1,
            name: file.basename,
            summary: `(Error summarising this note: ${err.message})`
          });
        }
      }
      this.setStatusBarText("Reducing \u2014 generating insight report...");
      const numberedSummaries = summaries.map(
        (s) => `[${s.index}] "${s.name}": ${s.summary}`
      ).join("\n");
      const insightReport = await this.apiClient.prompt(
        REDUCE_INSIGHT_SYSTEM_PROMPT,
        numberedSummaries,
        this.settings.aggregationTemperature
      );
      this.setStatusBarText("Writing insight report...");
      const reportFile = await this.createInsightReport(
        insightReport,
        summaries
      );
      new import_obsidian7.Notice(
        `Insight Report created: "${reportFile.basename}"`
      );
      await this.app.workspace.getLeaf(false).openFile(reportFile);
    } catch (err) {
      console.error("[Local Agent] Map-Reduce error:", err);
      new import_obsidian7.Notice(`Map-Reduce failed: ${err.message}`);
    } finally {
      this.isProcessing = false;
      this.setStatusBarText("");
    }
  }
  // ---- Map-Reduce Helpers -------------------------------------------------
  /**
   * Retrieve the most recently modified markdown files from a vault folder.
   * Sorted by modification time (newest first), limited by `maxFiles`.
   */
  async getRecentMarkdownFiles(folderPath, maxFiles) {
    const normalised = (0, import_obsidian7.normalizePath)(folderPath);
    const abstractFile = this.app.vault.getAbstractFileByPath(normalised);
    if (!abstractFile || !(abstractFile instanceof import_obsidian7.TFolder)) {
      new import_obsidian7.Notice(`Folder not found: "${folderPath}". Check your settings.`);
      return [];
    }
    const folder = abstractFile;
    const markdownFiles = [];
    const collectFiles = (f) => {
      for (const child of f.children) {
        if (child instanceof import_obsidian7.TFile && child.extension === "md") {
          markdownFiles.push(child);
        } else if (child instanceof import_obsidian7.TFolder) {
          collectFiles(child);
        }
      }
    };
    collectFiles(folder);
    markdownFiles.sort((a, b) => b.stat.mtime - a.stat.mtime);
    return markdownFiles.slice(0, maxFiles);
  }
  /**
   * Create a new Insight Report markdown file in the output folder.
   * The filename includes a timestamp to guarantee uniqueness.
   */
  async createInsightReport(reportContent, summaries) {
    const outputPath = (0, import_obsidian7.normalizePath)(this.settings.outputFolder);
    const existingFolder = this.app.vault.getAbstractFileByPath(outputPath);
    if (!existingFolder) {
      await this.app.vault.createFolder(outputPath);
    }
    const now = /* @__PURE__ */ new Date();
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now.toISOString().split("T")[1].replace(/:/g, "").substring(0, 6);
    const fileName = `Insight Report ${dateStr} ${timeStr}.md`;
    const filePath = (0, import_obsidian7.normalizePath)(`${outputPath}/${fileName}`);
    const sourceList = summaries.map((s) => `${s.index}. **${s.name}**: ${s.summary}`).join("\n");
    const fullReport = [
      "---",
      `type: insight-report`,
      `generated: ${now.toISOString()}`,
      `source_folder: "${this.settings.inputFolder}"`,
      `notes_processed: ${summaries.length}`,
      `model: "${this.settings.defaultModel}"`,
      "---",
      "",
      "# Insight Report",
      "",
      `> Generated by **Obsidian Local Agent** on ${dateStr} from ${summaries.length} notes in \`${this.settings.inputFolder}\`.`,
      "",
      reportContent,
      "",
      "---",
      "",
      "## Source Summaries",
      "",
      sourceList,
      ""
    ].join("\n");
    const file = await this.app.vault.create(filePath, fullReport);
    return file;
  }
  // ---- Utility ------------------------------------------------------------
  /**
   * Strip YAML frontmatter from a markdown string, returning only the body.
   */
  stripFrontmatter(content) {
    const fmRegex = /^---\s*\n[\s\S]*?\n---\s*\n?/;
    return content.replace(fmRegex, "").trim();
  }
};
